plan:
  title: "M@RS Authenticated Full Scan"
  description: "Authenticated active scan of M@RS with spider, AJAX spider, and comprehensive reporting"
  version: "1.0.0"

env:
  contexts:
    - name: M@RS
      urls:
        - ${TARGET_URL}/
      includePaths:
        - ${TARGET_URL}/.*
      authentication:
        method: form
        parameters:
          loginPageUrl: ${TARGET_URL}/login/login.xhtml
          loginRequestUrl: ${TARGET_URL}/login/login.xhtml
          loginRequestBody: 'loginguest=loginguest&loginguest:loginForm=loginguest:loginForm&loginguest:loginName={%username%}&loginguest:password={%password%}&loginguest:j_idt150=Sign+In&jakarta.faces.ViewState=stateless'
        verification:
          method: response
          loggedInRegex: '\QLogout\E'
          loggedOutRegex: '\QLogin\E'
      sessionManagement:
        method: cookie
      users:
        - name: si_owasp_user
          credentials:
            username: si_owasp_user
            password: TestPassword123!
  parameters:
    failOnError: true
    failOnWarning: false

jobs:
  - type: spider
    parameters:
      context: M@RS
      user: si_owasp_user
      maxDuration: 5

  - type: spiderAjax
    parameters:
      context: M@RS
      user: si_owasp_user
      maxDuration: 5

  - type: passiveScan-wait
    parameters:
      maxDuration: 2

  - type: activeScan
    parameters:
      context: M@RS
      user: si_owasp_user
      policy: Default Policy
      maxRuleDurationInMins: 10

  - type: passiveScan-wait
    parameters:
      maxDuration: 2

  - type: report
    parameters:
      template: traditional-html
      reportDir: ${REPORT_DIR}
      reportFile: auth-full-scan-report.html
      reportTitle: "ZAP Authenticated Full Scan - M@RS"

  - type: report
    parameters:
      template: traditional-json
      reportDir: ${REPORT_DIR}
      reportFile: auth-full-scan-report.json
      reportTitle: "ZAP Authenticated Full Scan - M@RS"

  - type: report
    parameters:
      template: traditional-md
      reportDir: ${REPORT_DIR}
      reportFile: auth-full-scan-report.md
      reportTitle: "ZAP Authenticated Full Scan - M@RS"

  - type: report
    parameters:
      template: traditional-xml
      reportDir: ${REPORT_DIR}
      reportFile: auth-full-scan-report.xml
      reportTitle: "ZAP Authenticated Full Scan - M@RS"

  - type: outputSummary
    parameters:
      format: LONG
      summaryFile: ${REPORT_DIR}/auth-full-scan-summary.json