plan:
  title: "M@RS AF Baseline"
  description: "Passive scan (no active attacks)"
  version: "1.0.0"

env:
  contexts:
    - name: "mars"
      urls:
        - "https://host.docker.internal:8443/benchmark"
  parameters:
    failOnError: true
    failOnWarning: false

jobs:
  - type: spider
    parameters:
      context: "mars"
      maxDuration: 2

  - type: spiderAjax
    parameters:
      context: "mars"
      maxDuration: 2

  - type: passiveScan-wait
    parameters:
      maxDuration: 2

  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk/reports/report-2025-11-15-4"
      reportFile: "baseline-report.html"
      reportTitle: "ZAP AF Baseline - M@RS"

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk/reports/report-2025-11-15-4"
      reportFile: "baseline-report.json"
      reportTitle: "ZAP AF Baseline - M@RS"

  - type: report
    parameters:
      template: "traditional-md"
      reportDir: "/zap/wrk/reports/report-2025-11-15-4"
      reportFile: "baseline-report.md"
      reportTitle: "ZAP AF Baseline - M@RS"

  - type: outputSummary
    parameters:
      format: LONG
      summaryFile: "/zap/wrk/reports/report-2025-11-15-4/baseline-summary.json"