plan:
  title: "M@RS AF Full Scan"
  description: "Active scan of M@RS"
  version: "1.0.0"

env:
  contexts:
    - name: "mars"
      urls:
        - "${TARGET_URL}"
  parameters:
    failOnError: true
    failOnWarning: false

jobs:
  - type: spider
    parameters:
      context: "mars"
      maxDuration: 2

  - type: spiderAjax
    parameters:
      context: "mars"
      maxDuration: 2

  - type: passiveScan-wait
    parameters:
      maxDuration: 2

  - type: activeScan
    parameters:
      context: "mars"
      policy: "Default Policy"
      maxRuleDurationInMins: 10

  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "${REPORT_DIR}"
      reportFile: "full-scan-report.html"
      reportTitle: "ZAP AF Full Scan - M@RS"

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "${REPORT_DIR}"
      reportFile: "full-scan-report.json"
      reportTitle: "ZAP AF Full Scan - M@RS"

  - type: report
    parameters:
      template: "traditional-md"
      reportDir: "${REPORT_DIR}"
      reportFile: "full-scan-report.md"
      reportTitle: "ZAP AF Full Scan - M@RS"

  - type: outputSummary
    parameters:
      format: LONG
      summaryFile: "${REPORT_DIR}/full-scan-summary.json"